# License Settings
license:
  key: "YOUR_LICENSE_KEY"

# Title Animation Settings
title:
  fade-in: 5
  stay: 40
  fade-out: 5

# Messages
messages:
  kill-title: "&a&l+%amount% $"
  kill-subtitle: "&f&lfor killing %victim%"
  death-title: "&c&l-%amount% $"
  death-subtitle: "&f&lKilled by %killer%"

# Sound Settings
# Sound names must match Bukkit Sound enum values
# View all valid sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sounds:
  kill:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP # Sound played when player kills someone
    volume: 1.0 # Volume range: 0.0 to 1.0
    pitch: 1.0 # Pitch range: 0.0 to 2.0
  death:
    enabled: true
    sound: ENTITY_VILLAGER_DEATH # Sound played when player dies
    volume: 1.0 # Volume range: 0.0 to 1.0
    pitch: 0.5 # Pitch range: 0.0 to 2.0

# Money Format Settings
format:
  quadrillion:
    suffix: "Q"
    enabled: true
  trillion:
    suffix: "T"
    enabled: true
  billion:
    suffix: "B"
    enabled: true
  million:
    suffix: "M"
    enabled: true
  thousand:
    suffix: "K"
    enabled: true
  decimal-places: 2

# Plugin Metrics
metrics:
  enabled: true # Set to false to disable bStats metrics collection

# Performance Settings
performance:
  # Balance tracker settings
  balance-tracker:
    # How long to wait before starting the balance tracker (in ticks, 20 ticks = 1 second)
    initial-delay: 20
    # How often to update balances (in ticks, 20 ticks = 1 second)
    # Lower values = more accurate but higher server load
    # Higher values = less accurate but lower server load
    interval: 10

# Player Statistics Settings
stats:
  # Enable or disable player statistics tracking
  enabled: true
  # How often to save stats to disk (in seconds)
  save-interval: 300
  # Worlds where stats GUI should be enabled
  # Use "all" to enable in all worlds, or specify a list of world names
  enabled-worlds:
  - "all"
  # Example of specific worlds:
  # - "world"
  # - "world_nether"
  # - "world_the_end"

  # Player Interaction Settings
player-interaction:
  # Show player ping when hovering crosshair over them
  show-ping-on-crosshair: true
  # Format for the ping display
  ping-format: "&e%player% &7- &aPing: &f%ping%ms"

  # Stats GUI settings
  stats-gui:
    # Enable or disable the stats GUI when clicking on players with empty hand
    enabled: true
    # Title of the stats GUI
    title: "&8Player Stats: &e%player%"
    # Sound to play when opening the GUI
    # View all valid sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    open-sound: BLOCK_CHEST_OPEN
    open-sound-volume: 0.5 # Volume range: 0.0 to 1.0
    open-sound-pitch: 1.0 # Pitch range: 0.0 to 2.0
